### ISSUE TITLE
How to the run crawler?

### ISSUE THREAD

**Issue by cyfdecyf** [zellux/paperoo#2]
`rake crawl:update` reports the following error:

```
No such file or directory - /Users/alex/Dropbox/programming/paperoo/db/raw_data/eurosys-11-0.endnote
```

**Comment by zellux** [comment]
Raw data are not included in the repository. Instead you can execute `rake db:data:load`, which loads db/data.yml into database.

**Comment by cyfdecyf** [comment]
Great, I can now fully replicate the environment. The import process is takes quite a while on my Mac. Create a board on Trello and decide what to do next?

**Comment by zellux** [comment]
Already there.
